import type { MetadataRoute } from 'next'
import { THEME_COLOR_BG } from '@/lib/theme'
import { site } from '@/content/site'

/**
 * The web app manifest.
 *
 * Deliberately thin. This site is not an application and has no offline story, so the
 * manifest exists to give an installed shortcut a name and a decent icon rather than to
 * claim capabilities the site does not have. `display: 'browser'` says exactly that: opened
 * from a home screen it is a page, not a standalone app pretending to be one.
 *
 * Both colours come from the same places the document does. `THEME_COLOR_BG` is the one hex
 * value that has to exist in JavaScript, for the reason in lib/theme.ts, and nothing here
 * duplicates a second.
 *
 * The 192 and 512 icons are the supplied mark contained on the light canvas, generated by
 * scripts/process-assets.py. They are `maskable: false` by omission, which is honest: the
 * lockup is 2.124 aspect and a maskable icon has to survive a circular crop, which this
 * cannot. A square glyph would fix it and none was supplied. See docs/BLOCKERS.md item 2.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: site.name,
    short_name: site.brand,
    description: site.descriptor,
    start_url: '/',
    display: 'browser',
    background_color: THEME_COLOR_BG,
    theme_color: THEME_COLOR_BG,
    icons: [
      { src: '/brand/icon-192.png', sizes: '192x192', type: 'image/png' },
      { src: '/brand/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
  }
}
