'use client'

import { useEffect, useRef } from 'react'
import {
  Camera,
  Color,
  LinearSRGBColorSpace,
  Mesh,
  PlaneGeometry,
  RepeatWrapping,
  Scene,
  ShaderMaterial,
  TextureLoader,
  Vector2,
  Vector3,
  WebGLRenderer,
} from 'three'
import type { VantaCloudsFactory, VantaEffect } from 'vanta/dist/vanta.clouds2.min'

/**
 * The clouds behind S6. Vanta's CLOUDS2 effect, on our terms. See ADR 0031.
 *
 * This is the fourth WebGL surface on the site, which `CLAUDE.md` allows only with
 * an ADR, and the first piece of motion here that we did not write. Four things had
 * to be true before it could be used at all, and each one is a line of code below
 * rather than an assumption:
 *
 * 1. **It must not reach the Reduced or Static tiers.** This module is only ever
 *    imported from the Full branch of a `TierGate`, dynamically, `ssr: false`, the
 *    same shape as `SceneLayer`. That is the rule the whole build rests on.
 * 2. **It must not pull in a second Three.js.** Vanta reads `window.THREE` by
 *    default, which is how its own snippet works and is not how anything here
 *    works. It also accepts a `THREE` option, so it gets ours, assembled from
 *    named imports. No script tag, no CDN, no second copy of the library, and no
 *    `import * as THREE`, which this codebase forbids.
 * 3. **It must not leak a context.** Vanta's `destroy()` removes its listeners and
 *    cancels its loop, then drops the renderer on the floor without disposing it.
 *    Ten mounts would be ten live contexts, so the cleanup below disposes and
 *    force-loses the context itself.
 * 4. **It must not cost what it renders at.** The shader raymarches 100 steps with
 *    four texture fetches each, so every pixel is expensive and a 2x display would
 *    ask for four times as many of them. The pixel ratio is capped.
 */

/**
 * Exactly the Three.js members Vanta touches, read out of its own source rather
 * than guessed: the base needs `WebGLRenderer` and `Scene`, the shader base needs
 * the rest. Named imports, so the bundler can still see what is unused elsewhere.
 */
const THREE_FOR_VANTA = {
  Camera,
  Color,
  Mesh,
  PlaneGeometry,
  Scene,
  ShaderMaterial,
  TextureLoader,
  Vector2,
  Vector3,
  WebGLRenderer,
}

/**
 * The ceiling on rendered pixels per CSS pixel. Vanta divides `devicePixelRatio`
 * by `scale`, so a bigger scale renders fewer pixels, which reads backwards until
 * you have read its `resize()`.
 *
 * 1.25 rather than the full 2 because the fragment shader costs 100 iterations and
 * 400 texture fetches per pixel, and because clouds are the one subject where a
 * softer render is invisible. This is the first number to move if it is slow.
 */
const MAX_PIXEL_RATIO = 1.25

/** Generated by `scripts/make-cloud-noise.py`, committed, served from our origin. */
const NOISE_TEXTURE = '/textures/clouds-noise.png'

/**
 * The brightest the field is allowed to be, as a display value. See ADR 0033.
 *
 * This is not a taste number, it is the contrast budget. The section's text is
 * `--color-fg-inverse`, whose relative luminance is 0.9222, and small text needs
 * 4.5:1. Solving that for the background gives a ceiling of L 0.166, which is a
 * display value of about 0.45. 0.40 is grey 102 at L 0.1329, which measures 5.32:1
 * and leaves headroom for the renderer, the grain and the dithering.
 *
 * Raising it above 0.45 makes the section fail WCAG AA. Nothing warns you.
 */
const FIELD_CEILING = 0.4

/**
 * The shader's own sky gradient, and the reason a token cannot be handed to it raw.
 *
 * `out1 = skyColor - d.w`, where `d.w = gl_FragCoord.y / iResolution.y - 0.65`. So
 * the sky runs from `skyColor + 0.65` at the bottom of the canvas to
 * `skyColor - 0.35` at the top: a fixed span of a full unit, whatever colour it is
 * given. There is no sky colour that renders evenly.
 *
 * Pre-subtracting the bottom offset is what puts the bright end of that gradient
 * exactly on the ceiling above. The top end lands below zero and clamps to black,
 * which is the section's own ground, so the field reads as a sky fading into it
 * rather than as a rectangle sitting on it.
 */
const SKY_BOTTOM_OFFSET = 0.65

/** The shadow side of a cloud, as a fraction of the ceiling. */
const CLOUD_LEVEL = 0.5

/**
 * A display value 0 to 1 per channel, from a CSS colour. Tokens are authored as hex
 * and computed to `rgb()`, and both are read here rather than assuming either.
 */
function readChannels(value: string): [number, number, number] | null {
  const hex = value.trim().match(/^#([0-9a-f]{6})$/i)
  if (hex?.[1]) {
    const n = Number.parseInt(hex[1], 16)
    return [((n >> 16) & 255) / 255, ((n >> 8) & 255) / 255, (n & 255) / 255]
  }
  const parts = value.match(/[\d.]+/g)
  if (!parts || parts.length < 3) return null
  const [r, g, b] = parts
  return [Number(r) / 255, Number(g) / 255, Number(b) / 255]
}

/**
 * The field's hue, taken from `--color-border-inverse` and normalised so its
 * brightest channel is 1. The token decides what colour the clouds are; the
 * constants above decide how bright they are allowed to be. Neither is guessed
 * and neither is a hex value written in this file.
 */
function readTint(): [number, number, number] {
  const styles = getComputedStyle(document.documentElement)
  const channels = readChannels(styles.getPropertyValue('--color-border-inverse'))
  if (!channels) return [1, 1, 1]
  const peak = Math.max(...channels)
  if (peak <= 0) return [1, 1, 1]
  return [channels[0] / peak, channels[1] / peak, channels[2] / peak]
}

/**
 * A colour the shader receives unchanged.
 *
 * Three converts sRGB to linear on the way in and the renderer converts back on the
 * way out, and this effect sits between the two: its output goes to the framebuffer
 * with no encoding, because that is what it was written against. So a colour handed
 * to it as a hex number arrives linearised and renders darker than it reads.
 * `setRGB` against the working colour space is the one path that assigns the exact
 * numbers, which is what makes the ceiling above mean anything.
 *
 * Values below zero are deliberate and survive: `Color.set` copies another Color
 * rather than clamping it, and the shader's gradient is what brings them back up.
 */
function exact(r: number, g: number, b: number): Color {
  return new Color().setRGB(r, g, b, LinearSRGBColorSpace)
}

/** See the union in `types/vanta.d.ts`. UMD interop, not defensive typing. */
function resolveFactory(loaded: {
  default: VantaCloudsFactory | { default: VantaCloudsFactory }
}): VantaCloudsFactory {
  const entry = loaded.default
  return typeof entry === 'function' ? entry : entry.default
}

export function CloudsScene() {
  const hostRef = useRef<HTMLDivElement | null>(null)

  useEffect(() => {
    const host = hostRef.current
    if (!host) return

    let cancelled = false
    let effect: VantaEffect | null = null

    const run = async () => {
      const factory = resolveFactory(await import('vanta/dist/vanta.clouds2.min'))
      if (cancelled || !hostRef.current) return

      const pixelRatio = window.devicePixelRatio || 1

      const [tr, tg, tb] = readTint()
      const level = (value: number) => [tr * value, tg * value, tb * value] as const

      const [skyR, skyG, skyB] = level(FIELD_CEILING)
      const [cloudR, cloudG, cloudB] = level(FIELD_CEILING * CLOUD_LEVEL)
      const [lightR, lightG, lightB] = level(FIELD_CEILING)

      effect = factory({
        el: host,
        THREE: THREE_FOR_VANTA,
        mouseControls: true,
        touchControls: true,
        gyroControls: false,
        minHeight: 200,
        minWidth: 200,
        scale: Math.max(1, pixelRatio / MAX_PIXEL_RATIO),
        texturePath: NOISE_TEXTURE,
        /*
          The sky is offset by the gradient the shader adds back, so its bright end
          lands on the ceiling and its dark end clamps into the section's ground.
        */
        skyColor: exact(
          skyR - SKY_BOTTOM_OFFSET,
          skyG - SKY_BOTTOM_OFFSET,
          skyB - SKY_BOTTOM_OFFSET,
        ),
        /* The shadow side, and the lit edge. Neither may pass the ceiling. */
        cloudColor: exact(cloudR, cloudG, cloudB),
        lightColor: exact(lightR, lightG, lightB),
      })

      const renderer = effect.renderer
      if (renderer) {
        /*
          The effect was written against Three r121, where the renderer wrote shader
          output through unchanged. Since r152 the default converts linear to sRGB on
          the way out, which lifts every midtone and turns this sky into a washed pale
          blue that looks nothing like the effect its author shipped. Setting the
          output back to linear is what makes our render match the reference.
        */
        renderer.outputColorSpace = LinearSRGBColorSpace
      }

      /*
        The shader wraps its own coordinates with fract(), so sampling never leaves
        0 to 1 and clamping is almost right. Almost: linear filtering across the last
        texel interpolates towards the clamped edge instead of towards the far side,
        which draws a faint grid on a texture built to tile. Repeat wrapping removes it.
      */
      const texture = effect.uniforms?.iTex?.value
      if (texture) {
        texture.wrapS = RepeatWrapping
        texture.wrapT = RepeatWrapping
        texture.needsUpdate = true
      }
    }

    void run()

    return () => {
      cancelled = true
      /*
        Read the renderer before destroy(), which nulls the field. Vanta disposes the
        scene and stops the loop but never the context, and browsers allow a small
        number of live contexts before they start dropping the oldest. Losing the
        hero's context to a section background would be a bad trade.
      */
      const renderer = effect?.renderer ?? null
      effect?.destroy()
      renderer?.dispose()
      renderer?.forceContextLoss()
      effect = null
    }
  }, [])

  /*
    Vanta appends its canvas to this element and, for any child it finds already
    inside, rewrites `position` and `z-index` inline. So it gets an element of its
    own with nothing in it, rather than the section.
  */
  return <div ref={hostRef} aria-hidden="true" className="absolute inset-0" />
}
