'use client'

import { useEffect, useRef } from 'react'
import {
  Camera,
  Color,
  LinearSRGBColorSpace,
  Mesh,
  PlaneGeometry,
  RepeatWrapping,
  Scene,
  ShaderMaterial,
  TextureLoader,
  Vector2,
  Vector3,
  WebGLRenderer,
} from 'three'
import type { VantaCloudsFactory, VantaEffect } from 'vanta/dist/vanta.clouds2.min'

/**
 * The clouds behind S6. Vanta's CLOUDS2 effect, on our terms. See ADR 0031.
 *
 * This is the fourth WebGL surface on the site, which `CLAUDE.md` allows only with
 * an ADR, and the first piece of motion here that we did not write. Four things had
 * to be true before it could be used at all, and each one is a line of code below
 * rather than an assumption:
 *
 * 1. **It must not reach the Reduced or Static tiers.** This module is only ever
 *    imported from the Full branch of a `TierGate`, dynamically, `ssr: false`, the
 *    same shape as `SceneLayer`. That is the rule the whole build rests on.
 * 2. **It must not pull in a second Three.js.** Vanta reads `window.THREE` by
 *    default, which is how its own snippet works and is not how anything here
 *    works. It also accepts a `THREE` option, so it gets ours, assembled from
 *    named imports. No script tag, no CDN, no second copy of the library, and no
 *    `import * as THREE`, which this codebase forbids.
 * 3. **It must not leak a context.** Vanta's `destroy()` removes its listeners and
 *    cancels its loop, then drops the renderer on the floor without disposing it.
 *    Ten mounts would be ten live contexts, so the cleanup below disposes and
 *    force-loses the context itself.
 * 4. **It must not cost what it renders at.** The shader raymarches 100 steps with
 *    four texture fetches each, so every pixel is expensive and a 2x display would
 *    ask for four times as many of them. The pixel ratio is capped.
 */

/**
 * Exactly the Three.js members Vanta touches, read out of its own source rather
 * than guessed: the base needs `WebGLRenderer` and `Scene`, the shader base needs
 * the rest. Named imports, so the bundler can still see what is unused elsewhere.
 */
const THREE_FOR_VANTA = {
  Camera,
  Color,
  Mesh,
  PlaneGeometry,
  Scene,
  ShaderMaterial,
  TextureLoader,
  Vector2,
  Vector3,
  WebGLRenderer,
}

/**
 * The ceiling on rendered pixels per CSS pixel. Vanta divides `devicePixelRatio`
 * by `scale`, so a bigger scale renders fewer pixels, which reads backwards until
 * you have read its `resize()`.
 *
 * 1.25 rather than the full 2 because the fragment shader costs 100 iterations and
 * 400 texture fetches per pixel, and because clouds are the one subject where a
 * softer render is invisible. This is the first number to move if it is slow.
 */
const MAX_PIXEL_RATIO = 1.25

/** Generated by `scripts/make-cloud-noise.py`, committed, served from our origin. */
const NOISE_TEXTURE = '/textures/clouds-noise.png'

/** See the union in `types/vanta.d.ts`. UMD interop, not defensive typing. */
function resolveFactory(loaded: {
  default: VantaCloudsFactory | { default: VantaCloudsFactory }
}): VantaCloudsFactory {
  const entry = loaded.default
  return typeof entry === 'function' ? entry : entry.default
}

export function CloudsScene() {
  const hostRef = useRef<HTMLDivElement | null>(null)

  useEffect(() => {
    const host = hostRef.current
    if (!host) return

    let cancelled = false
    let effect: VantaEffect | null = null

    const run = async () => {
      const factory = resolveFactory(await import('vanta/dist/vanta.clouds2.min'))
      if (cancelled || !hostRef.current) return

      const pixelRatio = window.devicePixelRatio || 1

      effect = factory({
        el: host,
        THREE: THREE_FOR_VANTA,
        mouseControls: true,
        touchControls: true,
        gyroControls: false,
        minHeight: 200,
        minWidth: 200,
        scale: Math.max(1, pixelRatio / MAX_PIXEL_RATIO),
        texturePath: NOISE_TEXTURE,
      })

      const renderer = effect.renderer
      if (renderer) {
        /*
          The effect was written against Three r121, where the renderer wrote shader
          output through unchanged. Since r152 the default converts linear to sRGB on
          the way out, which lifts every midtone and turns this sky into a washed pale
          blue that looks nothing like the effect its author shipped. Setting the
          output back to linear is what makes our render match the reference.
        */
        renderer.outputColorSpace = LinearSRGBColorSpace
      }

      /*
        The shader wraps its own coordinates with fract(), so sampling never leaves
        0 to 1 and clamping is almost right. Almost: linear filtering across the last
        texel interpolates towards the clamped edge instead of towards the far side,
        which draws a faint grid on a texture built to tile. Repeat wrapping removes it.
      */
      const texture = effect.uniforms?.iTex?.value
      if (texture) {
        texture.wrapS = RepeatWrapping
        texture.wrapT = RepeatWrapping
        texture.needsUpdate = true
      }
    }

    void run()

    return () => {
      cancelled = true
      /*
        Read the renderer before destroy(), which nulls the field. Vanta disposes the
        scene and stops the loop but never the context, and browsers allow a small
        number of live contexts before they start dropping the oldest. Losing the
        hero's context to a section background would be a bad trade.
      */
      const renderer = effect?.renderer ?? null
      effect?.destroy()
      renderer?.dispose()
      renderer?.forceContextLoss()
      effect = null
    }
  }, [])

  /*
    Vanta appends its canvas to this element and, for any child it finds already
    inside, rewrites `position` and `z-index` inline. So it gets an element of its
    own with nothing in it, rather than the section.
  */
  return <div ref={hostRef} aria-hidden="true" className="absolute inset-0" />
}
